# This optional file is included from the main Nginx context.
rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application tv {
            live on;
            record off;
            deny play all;

            notify_method post;
            on_publish http://127.0.0.1:8080/rtmp/auth.php;

            hls on;
            hls_path /var/lib/nginx/hls;
            hls_cleanup on;
            hls_nested on;
            hls_fragment_naming system;
            hls_allow_client_cache off;
            hls_fragment 10s;
            hls_playlist_length 60s;
        }
    }
}
